/** Page-specific copy for CUDA vs GPU service pages. Single object to avoid duplicated structure. */
export const SERVICE_PAGE_CONTENT = {
  cuda: {
    seo: {
      title: 'CUDA Development Services | Expert CUDA Developers for GPU Computing',
      description: 'Hire experienced CUDA developers to build high-performance GPU applications. Jashom delivers scalable CUDA development solutions for AI, deep learning, and parallel computing.',
      keywords: 'CUDA development, CUDA developers, GPU computing, parallel computing, CUDA programming',
    },
    heroImage: '/images/cuda.service.hero.jpg',
    heroImageStyle: 'top' as const,
    heroTitle: 'Custom CUDA Development for Advanced GPU Computing',
    heroSubtitle: 'Revolutionize computational pressure to run scalable performance using master CUDA engineering. Our architectures are built and deployed in the form of GPU-native, which opens the door to the efficiency of parallel processing of the AI systems, simulations, and data-intensive programs.',
    overviewTitle: 'What CUDA Means for\nYour Architecture',
    overviewSubtitle: 'Redefining Performance with GPU Parallelism',
    overviewParagraphs: [
      'CUDA development is concentrated on reengineering applications that perform effectively in thousands of cores of GPUs at the same time. Workloads are separated into parallel operations that are optimized to high throughput environments, rather than creating sequential CPU execution.',
      'Such a solution will minimize latency, optimize the use of resources, and increase the scalability of machine learning, quantitative analytics, visualization engines, and scientific modeling systems. The correct use of CUDA is not acceleration; it is an architectural change.',
    ],
    overviewStat1: { value: '100x', label: 'Compute Throughput Increase' },
    overviewStat2: { value: 'Up to 50%', label: 'Hardware Efficiency Optimization' },
    overviewImage: { src: '/images/cuda.developer.jpg', alt: 'CUDA Development' },
    servicesTitle: 'End-to-End CUDA Solutions for\nHigh-Performance Computing',
    servicesIntro: 'From kernel design to system integration, we deliver full-stack CUDA development that meets the most demanding performance and scalability requirements.',
    industryTitle: 'Accelerating Compute-Intensive\nIndustries',
    industryIntro: 'We design CUDA-driven solutions to industries whose speed of processing has a direct consequence on the results of their operation.',
    industryImage: null,
    processTitleMain: 'Structured CUDA ',
    processTitleGradient: 'Implementation Process',
    processSubtitle: 'A Six-Phase GPU Engineering Model',
    processIntro: 'Our design guarantees high availability, acceleration, and system integrity as well as scalability.',
    processCta: 'Start Your Development Journey',
    benefitsTitle: 'Strategic Benefits of\nCUDA Development',
    whyChooseTitle: 'Why Organizations Trust\nOur CUDA Team',
    testimonialsHeading: 'Client Experiences',
    testimonialsIntro: 'Proven Impact Across Industries',
    testimonialDisplay: 'roleCompany' as const,
    formTitle: 'Get Started with CUDA Development',
    formIdPrefix: 'cuda',
    showCtaBanner: false,
    showAiModels: false,
  },
  gpu: {
    seo: {
      title: 'NVIDIA GPU Optimization Services | Optimize NVIDIA GPU Performance',
      description: 'Improve speed and efficiency with expert NVIDIA GPU optimization services. We help businesses optimize NVIDIA GPU performance for AI, HPC, and data-intensive applications.',
      keywords: 'GPU optimization, NVIDIA GPU, GPU performance, AI acceleration, HPC optimization',
    },
    heroImage: '/images/service-hero-bg.jpg',
    heroImageStyle: 'center' as const,
    heroTitle: 'GPU Optimization Services',
    heroSubtitle: 'We provide advanced GPU Optimization Services, used to maximize your computing infrastructure to full performance. Our team optimizes workload patterns, execution pipes, and parallel processing to remove bottlenecks.',
    overviewTitle: 'What is GPU\nOptimization?',
    overviewSubtitle: null,
    overviewParagraphs: [
      'GPU optimization is a performance engineering science that aims at making the best use of throughput in a parallel computing system. It requires workload profiling, CUDA kernel restructuring, thread synchronization optimization, and efficient use of memory access to deliver consistent high-performance execution on modern hardware.',
      'Training time can also be minimized by optimized workloads on GPUs, infrastructure waste is minimized, and AI, scientific simulations, and data analytics apps are able to achieve higher compute densities. The result is accelerated processing, optimal use of hardware for compute-intensive processes, and cost-sustainability.',
    ],
    overviewStat1: { value: '10x', label: 'Faster Execution' },
    overviewStat2: { value: '40%', label: 'Reduced Compute Costs' },
    overviewImage: { src: '/images/gpu.jpg', alt: 'GPU Optimization' },
    servicesTitle: 'Optimize Performance That\nDrives Real Results',
    servicesIntro: 'Our engineers integrate CUDA Development Services with profound architectural experience to increase the use of a GPU on a wide range of workloads.',
    industryTitle: 'Industry-Focused GPU\nOptimization Solutions',
    industryIntro: 'Our GPU optimization services are designed to satisfy the computational needs of industry-specific situations. Each of our solutions is differentiated based on workload complexity, goals, and scalability goals.',
    industryImage: { src: '/images/gpu.service1.png', alt: 'Industry-Specific GPU Solutions' },
    processTitleMain: 'GPU Optimization ',
    processTitleGradient: 'Journey',
    processSubtitle: 'GPU Optimization Journey',
    processIntro: 'A dedicated six-step model to attain regular improvement in the performance of GPUs.',
    processCta: 'Start Your Optimization Journey',
    benefitsTitle: 'Business Benefits of\nGPU Optimization',
    whyChooseTitle: 'Why Choose Us for\nGPU Optimization?',
    testimonialsHeading: 'What Our Clients Say',
    testimonialsIntro: 'Trusted by forward-thinking organizations to deliver high-performance GPU and CUDA solutions.',
    testimonialDisplay: 'nameRole' as const,
    formTitle: 'Get Started with GPU Optimization',
    formIdPrefix: 'gpuopt',
    showCtaBanner: true,
    showAiModels: true,
  },
} as const;

export type ServicePageVariant = keyof typeof SERVICE_PAGE_CONTENT;
